name: Build and deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build wheel and SDist
      run: pipx run build

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*

    - name: Check metadata
      run: pipx run twine check dist/*


  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN_GENMQ }}
